In [8]:
import models
import torch
import os
model_name = 'output/colbert_cq_test-2023-05-17/700/0_ColBERTTransformerCQ/'
word_embedding_model =  models.ColBERTTransformerCQ(model_name, max_seq_length=256, dim = 128)
checkpoint = torch.load(os.path.join(model_name, "checkpoint.pt"), map_location='cpu')
word_embedding_model.load_state_dict(checkpoint)

<All keys matched successfully>

In [9]:
para1 = []
for p in word_embedding_model.parameters():
    para1.append(p)

In [10]:
import models
import torch
import os
model_name = 'output/colbert_cq_test-2023-05-17/700/0_ColBERTTransformerCQ/'
word_embedding_model =  models.ColBERTTransformerCQ(model_name, max_seq_length=256, dim = 128)
checkpoint = torch.load(os.path.join(model_name, "checkpoint.pt"), map_location='cpu')
word_embedding_model.load_state_dict(checkpoint)

<All keys matched successfully>

In [11]:
para2 = []
for p in word_embedding_model.parameters():
    para2.append(p)

In [12]:
for p1, p2 in zip(para1, para2):
    print(p1.tolist() == p2.tolist())

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [1]:
import cq_models
import torch
import os
model_name = 'output/colbert_cq_test-2023-05-17/700/1_CodeLearner/'
model =  cq_models.CodeLearner(emb_size = 128, M = 16, K = 256, hidden_size = 128)
checkpoint = torch.load(os.path.join(model_name, "pytorch_model.bin"), map_location='cpu')
model.load_state_dict(checkpoint)

<All keys matched successfully>

In [2]:
import cq_models
import torch
import os
model_name = '../../ContextualQuantizer/src/cq_models/model_2layer_new_16_256/epoch_193000.pt'
model =  cq_models.CodeLearner(emb_size = 128, M = 16, K = 256, hidden_size = 128)
checkpoint = torch.load(model_name, map_location='cpu')
model.load_state_dict(checkpoint)


<All keys matched successfully>

In [5]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[-0.0390, -0.0124, -0.0540,  ...,  0.0014, -0.0320,  0.0298],
        [ 0.0421,  0.0234,  0.0365,  ...,  0.0472, -0.0066,  0.0148],
        [-0.0601, -0.0215, -0.0300,  ...,  0.0589,  0.0201, -0.0368],
        ...,
        [-0.0074,  0.0162, -0.0343,  ..., -0.0375, -0.0430,  0.0305],
        [-0.0288, -0.0512, -0.0094,  ...,  0.0522,  0.0471,  0.0377],
        [ 0.0089, -0.0247,  0.0044,  ..., -0.0625, -0.0082,  0.0589]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0520, -0.0591, -0.0402,  0.0157, -0.0555, -0.0372, -0.0356,  0.0106,
         0.0458,  0.0092,  0.0213,  0.0563,  0.0298, -0.0062, -0.0355,  0.0240,
        -0.0067,  0.0283, -0.0370, -0.0305, -0.0109, -0.0384,  0.0380,  0.0004,
         0.0482, -0.0426,  0.0396,  0.0276, -0.0168, -0.0052,  0.0231,  0.0501,
        -0.0256,  0.0176, -0.0041, -0.0476,  0.0025, -0.0568, -0.0461,  0.0556,
         0.0430,  0.0137,  0.0552,  0.0494,  0.0030, -0.0282,  0.0179, -0.0090,
         0.0046

In [21]:

with torch.no_grad():
    word_embedding_model.cls.module.transform.dense.weight = torch.nn.Parameter(x['cls.predictions.transform.dense.weight'])
    word_embedding_model.cls.module.transform.dense.bias = torch.nn.Parameter(x['cls.predictions.transform.dense.bias'])
    word_embedding_model.cls.module.transform.LayerNorm.weight = torch.nn.Parameter(x['cls.predictions.transform.LayerNorm.weight'])
    word_embedding_model.cls.module.transform.LayerNorm.bias = torch.nn.Parameter(x['cls.predictions.transform.LayerNorm.bias'])
    word_embedding_model.cls.module.bias = torch.nn.Parameter(x['cls.predictions.bias'].repeat(3))
    word_embedding_model.cls.module.decoder.weight = torch.nn.Parameter(x['cls.predictions.decoder.weight'].repeat(3,1))
    word_embedding_model.cls.module.decoder.bias = torch.nn.Parameter(x['cls.predictions.decoder.bias'].repeat(3))

In [22]:
w3 = x['cls.predictions.decoder.weight'].repeat(3,1)

In [23]:
w3.shape

torch.Size([91566, 768])

In [25]:
op1 = w3.view(3, 30522, -1)

In [27]:
op1[0]

tensor([[-0.0389, -0.0761, -0.0617,  ..., -0.0482, -0.0597, -0.0184],
        [-0.0442, -0.0332,  0.0141,  ..., -0.0077, -0.0159, -0.0392],
        [-0.0403, -0.0679,  0.0146,  ...,  0.0318, -0.0262,  0.0031],
        ...,
        [-0.0263, -0.0573, -0.0065,  ...,  0.0549, -0.0242, -0.0405],
        [-0.0189, -0.0761,  0.0150,  ..., -0.0028, -0.0224, -0.0069],
        [ 0.0124, -0.0798, -0.0331,  ..., -0.0126, -0.0744,  0.0577]],
       device='cuda:0')

In [28]:
op1[1]

tensor([[-0.0389, -0.0761, -0.0617,  ..., -0.0482, -0.0597, -0.0184],
        [-0.0442, -0.0332,  0.0141,  ..., -0.0077, -0.0159, -0.0392],
        [-0.0403, -0.0679,  0.0146,  ...,  0.0318, -0.0262,  0.0031],
        ...,
        [-0.0263, -0.0573, -0.0065,  ...,  0.0549, -0.0242, -0.0405],
        [-0.0189, -0.0761,  0.0150,  ..., -0.0028, -0.0224, -0.0069],
        [ 0.0124, -0.0798, -0.0331,  ..., -0.0126, -0.0744,  0.0577]],
       device='cuda:0')

In [1]:
import torch
a = torch.rand([4, 11, 30])
a = a.repeat(1,1,3)

In [5]:
a[:,:,:30] == a[:,:,30:60]

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

In [2]:
x = a.reshape(4, 11, 3, -1)

In [3]:
x[:,:,0,:] == a[:,:,:30]

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

In [5]:
am = torch.argmax(x, dim=2)

In [7]:
x2 = torch.zeros_like(x).scatter_(1, am.unsqueeze(2), 1.) * x
o = x2.view(x2.shape[0], x2.shape[1], -1)

In [9]:
o[0,0,:]

tensor([0.3933, 0.2250, 0.0223, 0.2238, 0.7119, 0.6751, 0.4491, 0.1983, 0.2791,
        0.7427, 0.7661, 0.3680, 0.4497, 0.3924, 0.5574, 0.9438, 0.4204, 0.9841,
        0.2322, 0.2142, 0.4433, 0.8441, 0.7767, 0.9172, 0.8728, 0.3125, 0.1217,
        0.5486, 0.6127, 0.5870, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])

In [8]:
a = torch.tensor([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
a.view(3,8).view(3,2,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])